CREATE TABLE customer (
id INT(6) AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
country_code VARCHAR(2),
created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_date TIMESTAMP DEFAULT NULL,
is_active BOOLEAN NOT NULL DEFAULT TRUE
)