CREATE TABLE item (
id INT(6) AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) UNIQUE NOT NULL,
price DECIMAL(18,2) NOT NULL,
type VARCHAR(30),
created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_date TIMESTAMP DEFAULT NULL,
is_active BOOLEAN NOT NULL DEFAULT TRUE
)