CREATE TABLE orders (
id INT(6) AUTO_INCREMENT PRIMARY KEY,
order_stage VARCHAR(50) NOT NULL,
manager_name VARCHAR(255),
created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_date TIMESTAMP DEFAULT NULL,
is_active BOOLEAN NOT NULL DEFAULT TRUE
);